# GET http://localhost:3000
# Content-Type: application/json

# POST  http://localhost:3000/api/books
# Content-Type: application/json

# {
#   "title": "dxssdsssss",
#   "author": "Stephen Hawkisng",
#   "genre": "SCIENCE",
#   "isbn": "97810515a13sssssszdds3s8s0sx163",
#   "description": "An overview of cosmology and1 black holes.",
#   "copies": 10
# }

PUT  http://localhost:3000/api/books/685818021c54e1c08c6a3d92
Content-Type: application/json

{
  "copies": 0
}

# GET  http://localhost:3000/api/books/6858079913f3c117b832751b
# Content-Type: application/json

# POST  http://localhost:3000/api/borrow
# Content-Type: application/json

# {
#   "book": "68580408baf95c9a00f981cf",
#   "quantity": 2,
#   "dueDate": "3025-07-18T00:00:00.000Z"
# }

# GET  http://localhost:3000/api/borrow
# Content-Type: application/json

# GET http://localhost:3000/api/books?sort=asc&filter=science
# Content-Type: application/json
