# GET http://localhost:3000
# Content-Type: application/json

# POST  http://localhost:3000/api/books
# Content-Type: application/json

# {
#   "title": "dxssdssss",
#   "author": "Stephen Hawkisng",
#   "genre": "SCIsENCE",
#   "isbn": "97810515a13sssssszdds38s0sx163",
#   "description": "An overview of cosmology and1 black holes.",
#   "copies": 10
# }

PUT  http://localhost:3000/api/books/6856eb65f7313e540abc3bfd
Content-Type: application/json

{
  "copies": 0
}


# GET  http://localhost:3000/api/books?filter=science
# Content-Type: application/json

# POST  http://localhost:3000/api/borrow
# Content-Type: application/json

# {
#   "book": "6856a77b4ca1fcdfa62458ad",
#   "quantity": 2,
#   "dueDate": "3025-07-18T00:00:00.000Z"
# }

# GET  http://localhost:3000/api/borrow
# Content-Type: application/json

# GET http://localhost:3000/api/books?sort=asc&filter=science
# Content-Type: application/json
